spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  application:
    name: training-microservice
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  activemq:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
    packages:
      trust-all: true

server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

gym-crm-system:
  jwt:
    secret: "#1234"
    issuer: gym-crm-system
    expiration-in-milliseconds: 86400000

cors:
  origin:
    url: http://localhost:8080