spring:
  activemq:
    broker-url: tcp://local:61616
    user: artemis
    password: artemis
    packages:
      trust-all: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true